version: "3"

services:
  app:
    image: registry.devacceso.com/${IMAGENAME}:${CI_PIPELINE_ID}
    build: .
    restart: always
    ports:
      - "${PORTSALIDA}:${PORTDOCKER}"
    command: pm2-runtime server.config.js --env ${ENVDEPLOY}
    logging:
        driver: gelf
        options:
          gelf-address: "udp://192.168.4.239:12201"
          tag: ${DOCKER_STACK}
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.labels.name == ${NODO}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

